<?php

/**
 * Implements hook_entity_info().
 */
function patternentity_entity_info() {
  $return['patternentity'] = array(
    'label' => t('Pattern Entity'),
    'base table' => 'patternentity',
    'entity keys' => array(
      'id' => 'pid',
      'label' => 'title',
    ),
    'entity class' => 'PatternEntity',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'PatternEntityController',
    'admin ui' => array(
      'path' => 'admin/structure/patternentity',
      'file' => 'includes/patternentity.admin.inc',
    ),
    'module' => 'patternentity',
    'access callback' => 'patternentity_admin_access',
  );

  return $return;
}

/**
 * accesss callback function for hook_entity_info().
 */
function patternentity_admin_access($op, $profile = NULL, $account = NULL) {
  return user_access('administer patternentity', $account);
}

/**
 * Implements hook_permission().
 */
function patternentity_permission() {
  return array(
    'administer patternentity' => array(
      'title' => t('Administer patternentity'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function patternentity_menu() {
  $items = array();
  $items['pattern_entity_test'] = array(
    'title' => 'pattern entity test',
    'description' => 'pattern entity test des', 
    'page callback' => 'pattern_entity_test_page',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * callback hook_menu()
 */
function pattern_entity_test_page() {
  //$file = files_load();
  return "hello world";
}
