<?php

module_load_include('inc', 'patternentity', 'theme/theme');

/**
 * Implements hook_entity_info().
 */
function patternentity_entity_info() {
  $return['patternentity'] = array(
    'label' => t('Pattern Entity'),
    'base table' => 'patternentity',
    'entity keys' => array(
      'id' => 'pid',
      'label' => 'title',
    ),
    'entity class' => 'PatternEntity',
    'uri callback' => 'entity_class_uri',
    'controller class' => 'PatternEntityController',
    'admin ui' => array(
      'path' => 'admin/structure/patternentity',
      'controller class' => 'PatternEntityUIController',
      'file' => 'includes/patternentity.admin.inc',
    ),
    'module' => 'patternentity',
    'access callback' => 'patternentity_admin_access',
    'fieldable' => TRUE,
    'bundles' => array(
      'patternentity' => array(
        'label' => t('pattern entity bundle'),
        'admin' => array(
          'path' => 'admin/structure/patternentity',
          'access arguments' => array('administer patternentity'),
        ),
      ),
    ),

    'view modes' => array(
      'full pattern' => array(
        'label' => t('full for pattern'),
        'custom settings' => FALSE,
      ),
      'teaser pattern' => array(
        'label' => t('teaser for pattern'),
        'custom settings' => FALSE,
      ),
    ),
  );

  return $return;
}

/**
 * accesss callback function for hook_entity_info().
 */
function patternentity_admin_access($op, $profile = NULL, $account = NULL) {
  return user_access('administer patternentity', $account);
}

/**
 * Implements hook_permission().
 */
function patternentity_permission() {
  return array(
    'administer patternentity' => array(
      'title' => t('Administer patternentity'),
    ),
  );
}

/**
 * Implements hook_menu().
 */
function patternentity_menu() {
  $items = array();
  $items['pattern_entity_test'] = array(
    'title' => 'pattern entity test',
    'description' => 'pattern entity test des', 
    'page callback' => '_pattern_entity_test_page',
    'access callback' => TRUE,
  );

  $items['pattern/%'] = array(
    'title' => 'pattern view',
    'description' => 'pattern view page',
    'page callback' => '_pattern_entity_view_page',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );

  $items['pattern/%/download'] = array(
    'title' => 'pattern download link',
    'description' => 'pattern download menu link',
    'page callback' => '_pattern_entity_download_pattern',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * callback hook_menu() pattern/pid/download
 */
function _pattern_entity_download_pattern($pid) {
  $ety_obj = entity_object_load($pid, 'patternentity');
  $public_dir_path = variable_get('file_public_path', conf_path() . '/files');
  $file_path = substr_replace($ety_obj->file_path, $public_dir_path, 0, 8);
  header("Location: $file_path");
}

/**
 * callback hook_menu()
 */
function _pattern_entity_test_page() {
  //$file = files_load();
  return "hello world";
}

/**
 * callback for /pattern/pid
 */
function _pattern_entity_view_page($pid) {
  $pe = entity_object_load($pid, 'patternentity');
  drupal_set_title($pe->title);
  drupal_add_css(drupal_get_path('module', 'patternentity') . '/theme/patternentity.css');

  $content = _pattern_entity_view_pattern_description($pe);
  $content .= '<div id="patternentity-page-pattern-field">' . _pattern_entity_parser_field_pattern($pe->pattern) . '</div>';

  $field_view = entity_view('patternentity', array($pid => $pe));
  $content .= drupal_render($field_view);

  return $content;
}

